// <auto-generated />
using System;
using Infraestrutura.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dema.Infraestrutura.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250824011520_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Models.Demanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Atraso")
                        .HasColumnType("text");

                    b.Property<string>("ClientNR")
                        .HasColumnType("text");

                    b.Property<decimal>("Custo")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DataDeConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataDeEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataDeFechamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Desconto")
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("IDOrcamento")
                        .HasColumnType("integer");

                    b.Property<int>("IDResponsavel")
                        .HasColumnType("integer");

                    b.Property<int>("IDServico")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumServico")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("TipoCliente")
                        .HasColumnType("text");

                    b.Property<string>("Val_MaoDeObra")
                        .HasColumnType("text");

                    b.Property<string>("Val_Servico")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Demandas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
